on:
  workflow_call:
    inputs:
      etf_ticker:
        required: true
        type: string
      expected_rows:
        required: true
        type: string

name: Scrape Example ETFS
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build
        run: python3 -m pip install --user -e .
      - name: Scrape ETFS
        shell: bash
        run: |
          python3 scripts/scrape_etf.py --ticker ${{ inputs.etf_ticker }} >> holdings.csv

          NUM_HOLDINGS=$(cat holdings.csv | wc -l)

          echo "Found ${NUM_HOLDINGS} holdings for ${{ inputs.etf_ticker }}"

          if [ "${NUM_HOLDINGS}" -lt "${{ inputs.expected_rows }}" ]; then
            printf '%s\n' "Scraping for  failed for ticker ${{ inputs.etf_ticker }}" >&2
            exit 1
          fi
