name: IShares (IVV)

on:
  workflow_dispatch:
  schedule:
    - cron: "01 19 * * 1-5"

jobs:
  scrape:
    uses: ./.github/workflows/check-scraper.yml
    with:
      etf_ticker: IVV
      expected_rows: 495
